apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sample
  template:
    metadata:
      labels:
        app: redis-sample
    spec:
      containers:
        - name: redis
          image: redis:7.0
          ports:
            - containerPort: 6379
